
site_name: "CHEN 3201: Numerical Methods in Chemical Engineering Application, Spring 2021"

extra_css:
  - stylesheets/extra.css

theme:
    name: material
    palette:
        scheme: maroon
    favicon: 'umn-icon2.png'
    logo: 'umn-icon2.png'

nav:
  - About: index.md
  - Organization: organization.md
  - Calendar: calendar.md
  - Project: project.md
  - Resources: resources.md
